language: java
sudo: true
jdk:
  - oraclejdk8
cache:
  timeout: 1000
  directories:
  - $HOME/.m2
install:
    - if [ -e $HOME/.m2/repository/org/spigotmc ]; then echo "Installing dependencies..."; fi
  #  - [ -f $HOME/.m2/repository/org/spigotmc ] ||  && install_dependencies=true
   # - if [ "$install_dependencies" = true ] ; then mkdir lib fi
    #- if [ "$install_dependencies" = true ] ; then - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastStableBuild/artifact/target/BuildTools.jar -P lib/ fi
before_script:
  - sudo /etc/init.d/mysql stop
script:
    - cd /home/travis/build/Shynixn/BlockBall/lib/
    - java -jar BuildTools.jar --rev 1.8 > /dev/null
    - java -jar BuildTools.jar --rev 1.8.3 > /dev/null
    - java -jar BuildTools.jar --rev 1.8.8 > /dev/null
    - java -jar BuildTools.jar --rev 1.9 > /dev/null
    - java -jar BuildTools.jar --rev 1.9.4 > /dev/null
    - java -jar BuildTools.jar --rev 1.10 > /dev/null
    - java -jar BuildTools.jar --rev 1.11 > /dev/null
    - java -jar BuildTools.jar --rev 1.12 > /dev/null
    - cd -
    - mvn install