#######################################################################
#                          BlockBall                                  #
# 		            	   by Shynixn							      #
#######################################################################

# Permission:
# LEVEL		 DESCRIPTION									PERMISSION
# user       Access to join a blockball game				blockball.user.<game-id>
# user       Access to join every blockball game			blockball.user.all
# admin      Access to the /blockball command 				blockball.admin

############################

# Data-collecting settings

# Settings to send anonymous stats to https://bstats.org/plugin/bukkit/BlockBall.
# As this does not have an impact on your BlockBall experience at all I would like you to set it on true as knowing that my
# plugin gets used by many server helps me focusing on new updates ;)

############################

metrics: true

############################

# Arena configuration settings

# Join your server and create an arena via the ingame commands.
# You can edit the automatically created arena_x.yml files afterwards.

############################

############################

# Engine settings

# BlockBall uses a complex entity engine combining the power of armorstands and rabbits into
# ball movements. There are currently 2 available engines, however engine 2 is still in alpha
# and might cause issues during games.

############################

blockball:
 use-engine-v2: false

############################

# Messages settings

# Settings to adjust the messages

############################

messages:
  prefix: '&0&l[&f&lBall&0&l]&7 '
  state-sign-enabled: '&2&lENABLED'
  state-sign-disabled: '&4&lDISABLED'
  state-sign-running: '&1&lRUNNING'
  lobby-full: '&cLobby is full. You cannot join!'
  no-perms: '&cYou do not have permissions.'

############################

# Database settings

# All player stats are stored in a local file by default.
# It is recommend to edit these settings when you are using a MySQL database
# and have got a bigger player-base.

############################

sql:
  enabled: false
  host: localhost
  port: 3306
  database: ''
  username: ''
  password: ''

############################

# BungeeCord settings

# bungeecord-linking: Enable this to allow linking between other servers with BlockBall installed and linking enabled.
# bungeecord-low-resources: Enable this to only use the BlockBall signs to join on different servers.
#                           BlockBall will not be possible to play on this server if you enable this.
# bungeecord-mods: Mods which will be shown in the client server list and be used for linking players.
#                  All mods on all servers which have set linking to enabled HAVE TO set the exact same mods!!!
#

# HINT! Do not forget to enable the 'bungeecord-server-change' command below!

############################

bungeecord:
 linking: false
 low-resources: false
 mods:
   restarting-server: '&cRestarting...'
   waiting-for-players: '&aWaiting for players...'
   during-match: '&9Ingame'
 signs:
   states:
     restarting-server: '&c&lRestarting'
     waiting-for-players: '&a&lJoin'
     during-match: '&9&lIngame'
   lines:
     - '&l[BlockBall]'
     - '<server>'
     - '<state>'
     - '<players>/<maxplayers>'

############################

# Command settings

# Instead of setting the commands inside of the plugin.yml, I believe you should be able to customize
# the whole command by yourself. Name, description, permission customize it to your needs.

# global-join: Settings for the command to join games from any world on your server.
# global-leave: Settings for the command to leave games from any world on your server.
# global-leave: Settings for the command to adjust event games.

############################

global-join:
  enabled: true
  command: bbjoin
  useage: /<command> <game> <team>
  description: Join a game.
  permission: blockball.user
  permission-message: You don't have permission
global-leave:
  enabled: true
  command: bbleave
  useage: /<command>
  description: Leaves current game.
  permission: blockball.user
  permission-message: You don't have permission
referee-game:
  enabled: false
  command: bbreferee
  useage: /<command>
  description: Opens the configuration game section.
  permission: blockball.admin
  permission-message: You don't have permission
bungeecord-server-change:
  enabled: false
  command: bbbungee
  useage: /<command> <server>
  description: Creates blockball signs for joining different bungeecord servers.
  permission: blockball.admin
  permission-message: You don't have permission

############################

# Loading settings

# Settings to adjust the time after the plugin should be loaded. If there are
# not any issues when starting the server, leave it as it is.

############################

plugin-start-delay:
 enabled: false
 time-seconds: 20


############################

# Spawnpoint settings

# Settings to adjust the spawnpoints of players when the try to spawn in a blockball field
# after they have left the server.

############################

join-spawnpoint:
 enabled: false
 world: 'world'
 x: 0.0
 y: 0.0
 z: 0.0
 yaw: 0.0
 pitch: 0.0


############################

# Particles settings

# Settings to adjust the visibility of particles on low performance server.

############################

particles:
 visible-for-all: true
 visible-permission: ''

############################

# Stats settings

# Settings to adjust the scoreboard which displays certain player stats of BlockBall.

# enabled: Should scoreboard be displayed when a player joins your server?
# title: Title of the scoreboard.
# lines: Add or remove lines which are converted into the scoreboard lines.

# placeholders:
# <player> - Name of the player
# <player> - Name of the player
# <winrate> - Winrate of the player
# <playedgames> - Amount of played games
# <goalspergame> - Amount of goals per game

############################

stats-scoreboard:
 enabled: false
 title: '&f&lBlockBall Stats'
 lines:
   - ''
   - '&e<player>'
   - '&m           '
   - '&bWinrate: '
   - '&f&l<winrate> '
   - ''
   - '&6Goals per game: '
   - '&f&l<goalspergame>'
   - ''
   - '&aPlayed games:'
   - '&f&l<playedgames>'
   - '&m           '